watttime:
  username: comp
  password: Cl0ud#C0mpu

plan:
  folder: TerraformPlan

budget:
  # Threshold unit in g. Duration unit in h.
  threshold: 10
  duration: 48

opa:
  policy_file: carbon-policy.rego
